name: Feature Request
description: Suggest a new feature or enhancement
labels: ["feature"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the feature you'd like.
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Why is this feature needed? What problem does it solve?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or workarounds you've considered.
    validations:
      required: false